### ISSUE TITLE
RuntimeError when using schist.tl.select_affinity() a level is specified

### ISSUE THREAD

**Issue by leomorelli** [dawe/schist#2]
If I try to specify which level I want to select with scnsbm.tl.select_affinity(), a RunutimeError is raised:
`schist.tl.select_affinity(adata,level=2)
ERROR: Level 2 was not found in your data

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-22-00d264d15e19> in <module>
----> 1 schist.tl.select_affinity(adata,level=2)

~/anaconda3/envs/SCRNA/lib/python3.8/site-packages/schist/tools/_select.py in select_affinity(adata, level, threshold, inverse, key, update_state, filter, copy)
     54     if level not in adata.uns[key]['cell_affinity']:
     55         logg.error(f'Level {level} was not found in your data')
---> 56         raise
     57 
     58     affinities = adata.uns[key]['cell_affinity'][level]

RuntimeError: No active exception to reraise

`

**Comment by dawe** [comment]
Level keys are specified with strings, so `schist.tl.select_affinity(adata,level=2)` should be `schist.tl.select_affinity(adata,level='2')`. I've added a check in the function that converts integers to strings
