### ISSUE TITLE
Error with nested_model() options 

### ISSUE THREAD

**Issue by vgiansanti** [dawe/schist#3]
Hi!!!
If I try to use nested_model() with the collect_marginals and equilibrate options I have an error:

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-94-cb6982dfc0e1> in <module>
----> 1 nested_model(data, collect_marginals=True, equilibrate=True)

~/opt/anaconda3/envs/scanpy/lib/python3.7/site-packages/schist/inference/_nested_model.py in nested_model(adata, max_iterations, epsilon, equilibrate, wait, nbreaks, collect_marginals, niter_collect, hierarchy_length, deg_corr, multiflip, fast_model, n_init, beta_range, steps_anneal, resume, restrict_to, random_seed, key_added, adjacency, neighbors_key, directed, use_weights, prune, return_low, copy, minimize_args, equilibrate_args)
    285                                                mcmc_equilibrate_args=equilibrate_args,
    286                                                niter=steps_anneal,
--> 287                                                beta_range=beta_range)
    288     if collect_marginals and equilibrate:
    289         # we here only retain level_0 counts, until I can't figure out

~/opt/anaconda3/envs/scanpy/lib/python3.7/site-packages/graph_tool/inference/mcmc.py in mcmc_anneal(state, beta_range, niter, history, mcmc_equilibrate_args, verbose)
    264         else:
    265             S = ret[0]
--> 266             attempts += ret[1]
    267             nmoves += ret[2]
    268 

UnboundLocalError: local variable 'attempts' referenced before assignment

I have no problem if i just use nested_model(data).

Thanks!

**Comment by dawe** [comment]
It seems an issue related to `graph-tool`, which version are you using?

**Comment by vgiansanti** [comment]
I'm using the 2.29 version. I just finished running the function after patching graph-tool as you mention in the schist installation session and it works. But now I have problems with schist.tl.draw_graph():

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-1864105bef26> in <module>
----> 1 schist.tl.draw_graph(data)

~/opt/anaconda3/envs/scanpy/lib/python3.7/site-packages/schist/tools/_draw_graph.py in draw_graph(adata, layout, use_tree, random_seed, adjacency, key_added_ext, key, copy, **kwds)
    117         positions = np.array([x for x in positions][:n_cells])
    118     elif layout == 'sfdp':
--> 119         positions = gt.sfdp_layout(g)
    120         positions = np.array([x for x in positions][:n_cells])
    121     elif layout == 'arf':

AttributeError: module 'graph_tool.all' has no attribute 'sfdp_layout'

The same with fruchterman_reingold_layout

**Comment by dawe** [comment]
As for the version, I should add a strict dependency to `>=graph-tool=2.30`. 
I cannot reproduce the error for layout, instead. What if you type:

```python
>>> import graph_tool.all as gt
>>> gt.sfdp_layout
```

Do you get an error?

**Comment by vgiansanti** [comment]
Yes

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-ea3492d417a4> in <module>
----> 1 gt.sfdp_layout

AttributeError: module 'graph_tool.all' has no attribute 'sfdp_layout'

**Comment by dawe** [comment]
Mmm, could you try to update to `graph-tool>=2.30`? 

```
conda install -c conda-forge graph-tool=2.30
```

(we will update dependecies to 2.33 as it introduces a new model which would be great to introduce)
