### ISSUE TITLE
graph-tool patch no longer needed

### ISSUE THREAD

**Issue by count0** [dawe/schist#5]
The current version of graph-tool (2.33) no longer needs any patching, so maybe you should just tell users to upgrade.

**Comment by stuarteberg** [comment]
You can also drop the "Cairo interface" issue from the README. Presumably, it was only mentioned because conda-forge's `graph-tool` package used to lack plotting support.  It is now supported in recent versions.

**Comment by dawe** [comment]
I updated the documentation, thanks for the input.
