### ISSUE TITLE
scs.tl.label_transfer error

### ISSUE THREAD

**Issue by vgiansanti** [dawe/schist#59]
Hello!
I have this error when I apply scs.tl.label_transfer function (and I made sure the annotation is categorical):

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-cb0383980be0> in <module>
----> 1 scs.tl.label_transfer(rna_p, rna_u, obs='leiden_rna_u')

/beegfs/scratch/ric.cosr/giansanti.valentina/.conda/envs/dnn_cnv2/lib/python3.9/site-packages/schist/tools/_affinity_tools.py in label_transfer(adata, adata_ref, obs, label_unk, use_best, neighbors_key, adjacency, directed, use_weights, pca_args, use_rep, harmony_args, copy)
    461                                         batch_key='_label_transfer')
    462         #
--> 463         adata_merge.obs[obs] = adata_merge.obs[obs].cat.add_categories(label_unk).fillna(label_unk)
    464 
    465         # perform integration using harmony

/beegfs/scratch/ric.cosr/giansanti.valentina/.conda/envs/dnn_cnv2/lib/python3.9/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5459             or name in self._accessors
   5460         ):
-> 5461             return object.__getattribute__(self, name)
   5462         else:
   5463             if self._info_axis._can_hold_identifiers_and_holds_name(name):

/beegfs/scratch/ric.cosr/giansanti.valentina/.conda/envs/dnn_cnv2/lib/python3.9/site-packages/pandas/core/accessor.py in __get__(self, obj, cls)
    178             # we're accessing the attribute of the class, i.e., Dataset.geo
    179             return self._accessor
--> 180         accessor_obj = self._accessor(obj)
    181         # Replace the property with the accessor object. Inspired by:
    182         # https://www.pydanny.com/cached-property.html

/beegfs/scratch/ric.cosr/giansanti.valentina/.conda/envs/dnn_cnv2/lib/python3.9/site-packages/pandas/core/arrays/categorical.py in __init__(self, data)
   2455 
   2456     def __init__(self, data):
-> 2457         self._validate(data)
   2458         self._parent = data.values
   2459         self._index = data.index

/beegfs/scratch/ric.cosr/giansanti.valentina/.conda/envs/dnn_cnv2/lib/python3.9/site-packages/pandas/core/arrays/categorical.py in _validate(data)
   2464     def _validate(data):
   2465         if not is_categorical_dtype(data.dtype):
-> 2466             raise AttributeError("Can only use .cat accessor with a 'category' dtype")
   2467 
   2468     def _delegate_property_get(self, name):

AttributeError: Can only use .cat accessor with a 'category' dtype

**Comment by dawe** [comment]
Would you try if 1643d778901ce8bb14d60af5631771d1f801fc96 solves your issue?

**Comment by vgiansanti** [comment]
Yes! Thank you, now it is working!!
