### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by imerelli** [dawe/schist#62]
Hi, I'm trying schist with a Seurat converted object, but I encountered the error below. Any suggestions on how to proceed?

adata

AnnData object with n_obs × n_vars = 4015 × 15309
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'RNA_Condition', 'percent.mt', 'S.Score', 'G2M.Score', 'Phase', 'old.ident', 'CC.Difference', 'RNA_snn_h.orig.ident_res.0.6', 'seurat_clusters', 'RNA_snn_f.orig.ident_res.0.6', 'RNA_snn_m.orig.ident_res.0.6', 'RNA_snn_h.orig.ident_res.1.2', 'RNA_snn_f.orig.ident_res.1.2', 'RNA_snn_m.orig.ident_res.1.2', 'RNA_snn_h.orig.ident_res.1.8', 'RNA_snn_f.orig.ident_res.1.8', 'RNA_snn_m.orig.ident_res.1.8', 'SingleR_BlueprintEncodeData_labels', 'SingleRrefined_BlueprintEncodeData_labels', 'SingleR_HumanPrimaryCellAtlasData_labels', 'SingleRrefined_HumanPrimaryCellAtlasData_labels', 'SingleR_MonacoImmuneData_labels', 'SingleRrefined_MonacoImmuneData_labels', 'SingleR_DatabaseImmuneCellExpressionData_labels', 'SingleRrefined_DatabaseImmuneCellExpressionData_labels', 'SingleR_NovershternHematopoieticData_labels', 'SingleRrefined_NovershternHematopoieticData_labels'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    uns: 'neighbors'
    obsm: 'X_fastmnn.orig.ident', 'X_harmony.orig.ident', 'X_pca', 'X_tsne.fastmnn.orig.ident', 'X_tsne.harmony.orig.ident', 'X_tsne.merge.orig.ident', 'X_umap.fastmnn.orig.ident', 'X_umap.harmony.orig.ident', 'X_umap.merge.orig.ident'
    varm: 'FASTMNN.ORIG.IDENT', 'HARMONY.ORIG.IDENT', 'PCs'
    obsp: 'distances'

scs.inference.nested_model(adata)

/DATA_NFS/anaconda3/envs/postsc/lib/python3.8/site-packages/schist/inference/_nested_model.py:145: FutureWarning: This location for 'connectivities' is deprecated. It has been moved to .obsp[connectivities], and will not be accesible here in a future version of anndata.
  adjacency = adata.uns[neighbors_key]['connectivities']

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[7], line 1
----> 1 scs.inference.nested_model(a)

File /DATA_NFS/anaconda3/envs/postsc/lib/python3.8/site-packages/schist/inference/_nested_model.py:145, in nested_model(adata, deg_corr, tolerance, n_sweep, beta, samples, collect_marginals, n_jobs, restrict_to, random_seed, key_added, adjacency, neighbors_key, directed, use_weights, save_model, copy, dispatch_backend)
    142         adjacency = adata.obsp[conn_key]
    143     else:
    144         # scanpy<=1.4.6 has sparse matrix here
--> 145         adjacency = adata.uns[neighbors_key]['connectivities']
    146 if restrict_to is not None:
    147     restrict_key, restrict_categories = restrict_to

File /DATA_NFS/anaconda3/envs/postsc/lib/python3.8/site-packages/anndata/compat/_overloaded_dict.py:98, in OverloadedDict.__getitem__(self, key)
     96 def __getitem__(self, key):
     97     if key in self.overloaded:
---> 98         return self.overloaded[key].get()
     99     else:
    100         return self.data[key]

File /DATA_NFS/anaconda3/envs/postsc/lib/python3.8/site-packages/anndata/compat/_overloaded_dict.py:160, in _adjacency_getter(ovld, key, adata)
    154 """For overloading:
    155 
    156 >>> mtx = adata.uns["neighbors"]["connectivities"]  # doctest: +SKIP
    157 >>> mtx = adata.uns["neighbors"]["distances"]  # doctest: +SKIP
    158 """
    159 _access_warn(key, f".obsp[{key}]")
--> 160 return adata.obsp[key]

File /DATA_NFS/anaconda3/envs/postsc/lib/python3.8/site-packages/anndata/_core/aligned_mapping.py:148, in AlignedActualMixin.__getitem__(self, key)
    147 def __getitem__(self, key: str) -> V:
--> 148     return self._data[key]

KeyError: 'connectivities'

**Comment by dawe** [comment]
Hello, I actually never tried to run schist on a converted object. In current `scanpy` objects the knn graph is in `adata.obsp[adj_key]` and the value for `adj_key` is specified in `adata.uns[neighbors_key]`. 
Nevertheless, you should be able to directly feed the function with the desired adjacency matrix for the knn graph setting `adjacency` in the arg list (directly passing the sparse matrix).
