### ISSUE TITLE
AttributeError: module 'schist' has no attribute 'inference'

### ISSUE THREAD

**Issue by ngvananh2508** [dawe/schist#64]
I am following single-cell best practice tutorial, when I ran this code:

import schist as scs

scs.inference.nested_model(adata, samples = 100, random_seed = 5678)

It raised this error.

I am using schist version 0.7.16+2.gb762b76

Thank you so much for assisting me!

**Comment by dawe** [comment]
Hello @ngvananh2508 , apologies for the late reply.
Would you mind to actually post the error message you got?

**Comment by ngvananh2508** [comment]
I am sorry but I do not hold the context now. If I confront it again, I will let you know.

Thank you.

**Comment by dawe** [comment]
Ok. In case feel free to reopen the issue. Closing right now
