### ISSUE TITLE
Alternative approach based on greedy merge-split MCMC

### ISSUE THREAD

**Issue by count0** [dawe/schist#7]
It may be worthwhile also adding an alternative strategy based on a simple greedy MCMC:
```
state = NestedBlockState(g)
delta = 1
while abs(delta) > 1e-6:
     delta = state.multiflip_mcmc_sweep(niter=10, beta=numpy.inf)[0]
```
This could be faster in some cases, while still providing good results.

**Comment by dawe** [comment]
As alternative to `gt.minimize_nested_blockmodel_dl()`? 
@leomorelli would you care doing some tests?

**Comment by count0** [comment]
Yes. You should also play with the threshold; 1e-6 might be a bit too strict.

**Comment by leomorelli** [comment]
Sure @dawe ! I will try with different thresholds
