### ISSUE TITLE
can't load new 0.9.1 version with python 3.9

### ISSUE THREAD

**Issue by daniel-spies** [dawe/schist#70]
when loading the package  I get the following error:

`  File "/home/spies.daniel/.conda/envs/cellrank/lib/python3.9/site-packages/schist/inference/_model.py", line 49, in <module>
    key_added: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

It's due to the format of defining the default value that is only used from python 3.10+ but not in previous versions I think

setting it to `key_added: Optional[str] = None` worked then. the same has to be done in _model_multi.py at lien 52

best
Daniel

**Comment by dawe** [comment]
Thanks for pointing this. I will update minimal python requirement to the conda recipe (it is now 3.8).

**Comment by dawe** [comment]
Should be fixed with 9977e28bde1ee9fa1cc8c7afc4eb19b9286ac56e

**Comment by dawe** [comment]
Should be fixed in conda-forge/schist-feedstock@9977e28bde1ee9fa1cc8c7afc4eb19b9286ac56e
