### ISSUE TITLE
Font size in plotting functions

### ISSUE THREAD

**Issue by leomorelli** [dawe/schist#9]
I was wondering if plotting functions should contain a parameter to set font size of group labels. 
In particular especially with schist.plotting.alluvial() group labels of lower levels often overlap.

**Comment by dawe** [comment]
Added in 14978dd56f90947ed017f4d19556cba18f593a1e. `legend_fontsize`, `legend_fontweight` control the font face for group names on the plot, `axis_fontsize`, `axis_fontweight` control the font face displaying levels
